DjangoPageRank/urls.py
from django.contrib import admin
from django.urls import path

from .views import get_home, get_result, recipe_detail
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_home, name='home'),
    path('result/', get_result, name='result'),
    path('recipe/<str:recipe_id>/', recipe_detail, name='detail'),
]

DjangoRecipesRank/urls.py
from django.contrib import admin
from django.urls import path

from .views import get_home, get_result, recipe_detail
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_home, name='home'),
    path('result/', get_result, name='result'),
    path('recipe/<str:recipe_id>/', recipe_detail, name='detail'),
]

DjangoPageRank/forms.py
from django import forms

from DjangoPageRank.enums import Enums


class SearchForm(forms.Form):
    text_search = forms.CharField(
        label="Words to retrieve",
        widget=forms.TextInput(attrs={'placeholder': 'Search your recipe'}),
        required=True
    )

    n_steps_min = forms.IntegerField(
        label="Minimum Number of Steps",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '1', 'max': '50', 'value': '1'})
    )

    n_steps_max = forms.IntegerField(
        label="Maximum Number of Steps",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '1', 'max': '50', 'value': '50'})
    )

    recipe_date_min = forms.IntegerField(
        label="Minimum Recipe Date",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '2000', 'max': '2024', 'value': '2000'})
    )

    recipe_date_max = forms.IntegerField(
        label="Maximum Recipe Date",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '2000', 'max': '2024', 'value': '2024'})
    )
    prep_time_min = forms.IntegerField(
        label="Minimum Preparation Time (minutes)",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '1', 'max': '10000', 'value': '1'})
    )

    prep_time_max = forms.IntegerField(
        label="Maximum Preparation Time (minutes)",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '1', 'max': '10000', 'value': '10000'})
    )

    rating = forms.IntegerField(
        label="Minimum rating",
        required=False,
        widget=forms.RadioSelect(choices=[(i, f"{i} ★") for i in range(0, 6)])
    )

    n_ingredients_min = forms.IntegerField(
        label="Minimum Number of Ingredients",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '1', 'max': '20', 'value': '1'})
    )

    n_ingredients_max = forms.IntegerField(
        label="Maximum Number of Ingredients",
        required=False,
        widget=forms.NumberInput(attrs={'type': 'range', 'min': '1', 'max': '20', 'value': '20'})
    )

    # use_sentiment = forms.BooleanField(
    #     label="Sentiment",
    #     required=False,
    #     widget=forms.CheckboxInput()
    # )

    selected_model = forms.ChoiceField(
        label="Choose Model",
        required=False,
        choices=Enums.Model.choices,
        widget=forms.Select()
    )

    chosen_sentiments = forms.MultipleChoiceField(
        label="Chosen Sentiments",
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices= [
            ('anger', 'Anger'),
            ('disgust', 'Disgust'),
            ('fear', 'Fear'),
            ('joy', 'Joy'),
            ('neutral', 'Neutral'),
            ('sadness', 'Sadness'),
            ('surprise', 'Surprise'),
        ]
    )

    number_of_results = forms.ChoiceField(
        label="Number of Results",
        choices=[(10, "10"), (15, "15"), (20, "20"), (25, "25"), (50, "50"), (100, "100")],
        required=False
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Recipe Finder{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.9.1/font/bootstrap-icons.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- jQuery UI JS -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <link rel="shortcut icon" type="image/png" href="{% static 'imgs/favicon.png' %}" >    

    <!-- Custom CSS (optional) -->
    <style>
        /* Ensure the whole page takes up at least 100% of the viewport height */
        html, body {
            height: 100%;
            margin: 0;
        }

        /* Flexbox layout: body stretches to fill the viewport */
        body {
            display: flex;
            flex-direction: column;
            /*background: linear-gradient(135deg, #f5f7fa 0%, #e9ecef 100%);*/
        }

        /* Main content area should expand to fill the available space */
        .container {
            flex: 1;
        }

        .header-logo {
            font-size: 1.5rem;
            font-weight: bold;
        }
        .navbar-custom {
            background-color: #ffcf6b;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .footer-custom {
            background-color: #e9ecef;
            box-shadow: 0 -2px 4px rgba(0,0,0,0.1);
            padding: 20px 0;
            margin-top: 20px;
        }
        .footer-text {
            text-align: center;
            margin: 0;
            font-size: 0.9rem;
        }
        .icon {
            margin-right: 10px;
            width: 30px;
            height: 30px;
        }
        
        .star-rating {
            display: inline-block;
            font-size: 2em;
            color: #ccc;
            margin-top: 10px;
        }

        .star {
            position: relative;
            display: inline-block;
            width: 1em;
            overflow: hidden;
        }

        .star.full {
            color: #f39c12;
        }

        .star.half::before,
        .star.quarter::before,
        .star.three-quarters::before {
            content: '\2605';
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            overflow: hidden;
            color: #f39c12;
        }

        .star.quarter::before {
            width: 35%;              /* Set to 35% instead of 25% for a better visualization*/
        }

        .star.half::before {
            width: 45%;              /* Set to 45% instead of 50% for a better visualization*/
        }

        .star.three-quarters::before {
            width: 55%;               /* Set to 55% instead of 75% for a better visualization*/
        }

        .star.empty {
            color: #ccc;
        }
        .star-rating span {
            font-size: 1.2em;
            line-height: 1.2em;
        }
        .btn-custom {
            margin-top: 10px;
            padding: 10px 20px;
            font-size: 1em;
            color: #fff;
            background-color: #4CAF50;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .btn-custom:hover {
            background-color: #45a049;
            color: #fff;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
        <div class="container-fluid">
            <a class="navbar-brand header-logo" href="{% url 'home' %}">
                <img src="{% static 'imgs/favicon.png' %}" alt="Recipe imgs" class="icon">
                Recipe Finder
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="footer-custom">
        <div class="container">
            <p class="footer-text">© 2024 Recipe Finder. All Rights Reserved.</p>
        </div>
    </footer>

    <!-- Bootstrap JS and dependencies (Optional if you need JavaScript functionalities) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <style>
        .rating-container {
            display: flex;
            align-items: center; 
            margin-top: 10px;
        }

        .star-rating {
            font-size: 2em;
            color: #ccc;
            display: inline-block;
        }

        .rating-value {
            font-size: 1.2em;
            margin-left: 10px;
            color: #333;
        }

        .back-button {
            position: absolute;
            top: 70px;
            left: 20px;
            padding: 10px 20px;
            z-index: 10;
        }
    </style>
    
    
<div class="container my-5">
    <input type="button" value="← Back" onClick="history.go(-1);" class="btn-custom back-button">
    <h1 class="display-4">{{ recipe.recipe_name }}</h1>
    <p class="lead">{{ recipe.description }}</p>

    <!-- Preparation Time with alert box to highlight it -->
    <div class="alert alert-warning" role="alert">
        <h3 class="alert-heading">Preparation Time</h3>
        <p>{{ recipe.prep_time }} minutes</p>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h3>Ingredients ({{ recipe.n_ingredients }})</h3>
            <ul class="list-group">
                {% with recipe.ingredients as ingredients %}
                    {% for ingredient in ingredients %}
                        <li class="list-group-item">• {{ ingredient }}</li>
                    {% endfor %}
                {% endwith %}
            </ul>
        </div>

        <!-- Radar Chart Section -->
        <div class="col-md-6">
            <h3>Mean Sentiment Score</h3><h6>(based on this recipe's reviews)</h6>
            <div style="width: 100%; max-width: 400px; margin: auto;">
                <canvas id="radarChart" width="300" height="300"></canvas>
            </div>
        </div>
    </div>

    <div style="padding: 0.5rem;"></div>

    <!-- Steps Section formatted like Ingredients -->
    <div>
        <h3>Steps ({{ recipe.n_steps }})</h3>
        <ul class="list-group">
            {% for step in recipe.steps %}
                <li class="list-group-item"><strong>Step {{ forloop.counter }}:</strong> <br>{{ step }}</li>
            {% endfor %}
        </ul>
    </div>

    <!-- Divider -->
    <div style="padding: 1.5rem;"></div>

    <!-- Reviews Section -->
    <h3>Reviews</h3>
    <div>
        {% if reviews %}
            <ul class="list-group">
                {% for review in reviews %}
                    <li class="list-group-item star-list" data-rating="{{ review.rating }}">
                        <strong>{{ review.user }}</strong>
                        <span class="text-muted">({{ review.date }})</span>
                        <p>{{ review.review|safe }}</p>
                        <div class="rating-container">
                           <div class="star-rating">
                                <span class="star empty">&#9733;</span>
                                <span class="star empty">&#9733;</span>
                                <span class="star empty">&#9733;</span>
                                <span class="star empty">&#9733;</span>
                                <span class="star empty">&#9733;</span>
                           </div>
                           <span class="rating-value">{{ recipe.rating }}</span><span>/5</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No reviews on this one.</p>
        {% endif %}
    </div>
</div>

<!-- Include Chart.js library -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script src="{% static 'js/star_rating.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const item = document.querySelectorAll('.list-group-item.star-list');
        item.forEach(container => {
            // Parse the rating and round it to two decimal places
            let rating = parseInt(container.dataset.rating);
            rating = Math.round(rating * 100) / 100;
            
            // Update the star rating display
            const starRatingElement = container.querySelector('.star-rating');
            viewStars(starRatingElement, rating);

            // Update the rating display next to the stars
            const ratingValueElement = container.querySelector('.rating-value');
            ratingValueElement.textContent = rating.toFixed(2); // Set the rounded rating value
        });
    });

    // Convert the Django context variables to JavaScript
    const labels = {{ sentiment_list|safe }};
    const data = {{ sentiment_vector|safe }};

    // Create the radar chart using Chart.js
    const ctx = document.getElementById('radarChart').getContext('2d');
    const radarChart = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: labels,
            datasets: [{
                data: data,
                backgroundColor: 'rgba(255,194,82,0.48)',
                borderColor: 'rgb(255,207,107)',
                borderWidth: 1
            }]
        },
        options: {
            scale: {
                ticks: {
                    beginAtZero: true,
                    max: 10
                }
            },
            plugins: {
                legend: {
                    display: false  // This hides the legend (label)
                }
            }
        }
    });
</script>
{% endblock %}

templates/homepage.html
{% extends 'base.html' %}

{% block title %}Home - Recipe Finder{% endblock %}

{% block content %}
<div class="search-container">
    <form class="search-box" method="post" action="{% url 'result' %}">
        {% csrf_token %}

        <div class="text-search-container">
            {{ form.text_search }}

            <div style="margin-left: 1rem">
                <strong><label for="{{ form.selected_model.id_for_label }}">{{ form.selected_model.label }}</label></strong>
                {{ form.selected_model }}
            </div>

        </div>

        <div class="sentiments-container">
            <label for="id_chosen_sentiments">{{ form.chosen_sentiments.label }}</label>
            <div class="sentiments-checkboxes">
                {% for value, label in form.chosen_sentiments.field.choices %}
                <div class="sentiment-checkbox">
                    <input type="checkbox" name="{{ form.chosen_sentiments.name }}" value="{{ value }}"
                        id="id_chosen_sentiments_{{ forloop.counter }}"
                        {% if value in form.chosen_sentiments.value %} checked {% endif %}>
                    <label for="id_chosen_sentiments_{{ forloop.counter }}">{{ label }}</label>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="number-of-results-container">
            <label for="id_number_of_results"><strong>{{ form.number_of_results.label }}</strong></label>
            {{ form.number_of_results }}
        </div>

        <div class="filters">
            <div class="filter-item">
                <label>Number of Steps</label>
                <div id="n_steps_slider"></div>
                <span id="n_steps_min_text">1</span> -
                <span id="n_steps_max_text">50</span>
                <input type="hidden" name="n_steps_min" id="n_steps_min" value="1">
                <input type="hidden" name="n_steps_max" id="n_steps_max" value="50">
            </div>

            <div class="filter-item">
                <label>Preparation Time (minutes)</label>
                <div id="prep_time_slider"></div>
                <span id="prep_time_min_text">1</span> -
                <span id="prep_time_max_text">300</span>
                <input type="hidden" name="prep_time_min" id="prep_time_min" value="1">
                <input type="hidden" name="prep_time_max" id="prep_time_max" value="300">
            </div>

            <div class="filter-item">
                <label>Number of Ingredients</label>
                <div id="n_ingredients_slider"></div>
                <span id="n_ingredients_min_text">1</span> -
                <span id="n_ingredients_max_text">20</span>
                <input type="hidden" name="n_ingredients_min" id="n_ingredients_min" value="1">
                <input type="hidden" name="n_ingredients_max" id="n_ingredients_max" value="20">
            </div>

            <div class="filter-item">
                <label>Select the year range</label>
                <div id="years_slider"></div>
                <span id="years_min_text">2000</span> -
                <span id="years_max_text">2024</span>
                <input type="hidden" name="recipe_date_min" id="years_min" value="2000">
                <input type="hidden" name="recipe_date_max" id="years_max" value="2024">
            </div>

            <label class="rating-label">{{ form.rating.label }}</label>
            <div class="star-rating">
                {% for i in "54321" %}
                <input type="radio" name="rating" value="{{ i }}" id="star{{ i }}"
                    {% if form.rating.value|stringformat:"s" == i %} checked {% endif %}>
                <label for="star{{ i }}">&#9733;</label>
                {% endfor %}
                <input type="radio" name="rating" value="0" id="star0"
                    {% if form.rating.value|stringformat:"s" == "0" %} checked {% endif %}>
                <label for="star0" style="display: none;">&#9733;</label>
            </div>
        </div>

        <button type="submit">Search</button>
    </form>
</div>

<!-- Include Select2 CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css" rel="stylesheet" />

<!-- Include jQuery, Select2, and jQuery UI CSS and JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/js/select2.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<style>
    .search-container {
        display: flex;
        justify-content: center;
        margin-top: 50px;
        width: 60%;
        margin-left: auto;
        margin-right: auto;
    }

    .search-box {
        width: 100%;
        position: relative;
    }

    .text-search-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 20px;
    }

    .search-box input[type="text"] {
        width: 70%;
        padding: 15px 20px;
        font-size: 18px;
        border-radius: 30px;
        border: 1px solid #ced4da;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
    }

    .search-box button {
        padding: 12px 20px;
        background-color: #4CAF50;
        border: none;
        border-radius: 30px;
        color: white;
        font-size: 18px;
        cursor: pointer;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
        display: block;
        width: 100%;
        text-align: center;
        transition: background-color 0.3s ease;
    }

    .search-box button:hover {
        background-color: #45a049;
    }

    .number-of-results-container {
        margin-bottom: 20px;
    }

    .filters {
        margin-top: 30px;
    }

    .filter-item {
        margin-bottom: 20px;
    }

    .filter-item label,
    .rating-label {
        display: block;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .filter-item div {
        display: inline-block;
        width: 75%;
    }

    .filter-item span {
        display: inline-block;
        width: 10%;
        text-align: center;
        font-weight: bold;
        font-size: 14px;
    }

    .rating-label {
        margin-bottom: 0;
    }

    .star-rating {
        display: flex;
        justify-content: left;
        flex-direction: row-reverse;
    }

    .star-rating input {
        display: none;
    }

    .star-rating label {
        font-size: 3rem;
        color: #ddd;
        cursor: pointer;
        padding: 0 10px;
    }

    .star-rating input:checked~label,
    .star-rating label:hover,
    .star-rating label:hover~label {
        color: #f39c12;
    }

    .sentiments-container {
        margin-bottom: 20px;
        display: none;
    }

    .sentiments-container label {
        display: block;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .sentiments-checkboxes {
        display: flex;
        flex-wrap: wrap;
    }

    .sentiment-checkbox {
        margin-right: 15px;
        margin-bottom: 10px;
        display: flex;
        align-items: center;
    }

    .sentiment-checkbox input[type="checkbox"] {
        margin-right: 8px;
    }

    .sentiment-checkbox label {
        font-size: 16px;
        cursor: pointer;
    }

    .ui-slider .ui-slider-handle {
        background-color: #deb351;
        border-radius: 50%;
        border: 2px solid #ffffff;
        width: 1.5rem;
        height: 1.5rem;
        top: -0.5rem;
    }

    .ui-slider-range {
        background-color: #ffcf6b;
    }

    input[type="text"], input[type="number"], select {
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ced4da;
        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);
    }
</style>

<script>
    $(document).ready(function() {
        $('select').select2({
            theme: 'classic'  // Puoi cambiare il tema qui
        });

        // Funzione per mostrare/nascondere il contenitore dei sentimenti
    function toggleSentimentsContainer() {
        if ($('#id_selected_model').val() === 'SE' || $('#id_selected_model').val() === 'RSE') {
            $('.sentiments-container').show(); // Usa la classe, non l'ID
        } else {
            $('.sentiments-container').hide();
        }
    }

    // Esegui la funzione quando la pagina viene caricata
    toggleSentimentsContainer();

    // Gestire il cambiamento del valore del menu a tendina
    $('#id_selected_model').change(function() {
        toggleSentimentsContainer();
    });

        $("#n_steps_slider").slider({
            range: true,
            min: 1,
            max: 50,
            values: [1, 50],
            slide: function(event, ui) {
                $("#n_steps_min").val(ui.values[0]);
                $("#n_steps_max").val(ui.values[1]);
                $("#n_steps_min_text").text(ui.values[0]);
                $("#n_steps_max_text").text(ui.values[1]);
            }
        });

        $("#prep_time_slider").slider({
            range: true,
            min: 1,
            max: 300,
            values: [1, 300],
            slide: function(event, ui) {
                $("#prep_time_min").val(ui.values[0]);
                $("#prep_time_max").val(ui.values[1]);
                $("#prep_time_min_text").text(ui.values[0]);
                $("#prep_time_max_text").text(ui.values[1]);
            }
        });

        $("#n_ingredients_slider").slider({
            range: true,
            min: 1,
            max: 20,
            values: [1, 20],
            slide: function(event, ui) {
                $("#n_ingredients_min").val(ui.values[0]);
                $("#n_ingredients_max").val(ui.values[1]);
                $("#n_ingredients_min_text").text(ui.values[0]);
                $("#n_ingredients_max_text").text(ui.values[1]);
            }
        });

        $("#years_slider").slider({
            range: true,
            min: 2000,
            max: 2024,
            values: [2000, 2024],
            slide: function(event, ui) {
                $("#years_min").val(ui.values[0]);
                $("#years_max").val(ui.values[1]);
                $("#years_min_text").text(ui.values[0]);
                $("#years_max_text").text(ui.values[1]);
            }
        });
    });

    document.addEventListener('DOMContentLoaded', function () {
            const star1Input = document.getElementById('star1');
            const star0Input = document.getElementById('star0');
            const star1Label = document.querySelector('label[for="star1"]');

            star1Label.addEventListener('click', function (event) {
                // If the first star is already selected
                if (star1Input.checked) {
                    // Prevent the default behavior of the label click
                    event.preventDefault();
                    // Deselect the first star by selecting the hidden 0-star input
                    star0Input.checked = true;
                    // Trigger change event to update form state
                    star0Input.dispatchEvent(new Event('change'));
                }
            });
        });
</script>

{% endblock %}

templates/result.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <style>
    .rating-container {
        display: flex;
        align-items: center; /* Align stars and rating value vertically */
        margin-top: 10px;
    }

    .star-rating {
        font-size: 2em;
        color: #ccc;
        display: inline-block;
    }

    .rating-value {
        font-size: 1.2em;
        margin-left: 10px;
        color: #333;
    }

    /* Card styles */
    .card {
        transition: transform 0.3s ease, box-shadow 0.3s ease; /* Smooth transition for scale and shadow */
        border: 1px solid #ddd; /* Light border */
        border-radius: 8px; /* Rounded corners */
    }

    /* Hover effect for cards */
    .card:hover {
        transform: scale(1.02); /* Scale up the card */
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2); /* Add shadow */
    }

    /* Style for the selected page */
    .pagination .page-item.active .page-link {
        background-color: #4CAF50;
        border-color: #4CAF50;
        color: white; /* Text color inside the green background */
    }

    /* Style for other page numbers */
    .pagination .page-item .page-link {
        color: black; /* Text color for non-active page numbers */
    }

    /* Style for the disabled arrow and default arrow */
    .pagination .page-item.disabled .page-link,
    .pagination .page-item .page-link span {
        color: black; /* Color of the arrows */
    }

    /* Style for hover and focus on pagination links */
    .pagination .page-item .page-link:hover,
    .pagination .page-item .page-link:focus {
        background-color: #f8f9fa; /* Light background on hover */
        color: black;
    }
    </style>


    <h1>Search Results</h1>
    
    <div class="row">
        <div class="col">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                {% for recipe in page_obj %}
                    <div class="col">
                        <a href="{% url 'detail' recipe.id %}" class="text-decoration-none text-dark">
                            <div class="card h-100">
                                <div class="card-body" data-rating="{{ recipe.rating }}">
                                    <span class="text-muted" style="align-content: flex-end;">({{ recipe.date }})</span>
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                    <div class="card-text">
                                        <ul>
                                            <li>Steps: {{ recipe.n_steps }}</li>
                                            <li>Number of ingredients: {{ recipe.n_ingredients }}</li>
                                            <li>Preparation time: {{ recipe.prep_time }} minutes</li>
                                        </ul>
                                       <div class="rating-container">
                                           <div class="star-rating">
                                                <span class="star empty">&#9733;</span>
                                                <span class="star empty">&#9733;</span>
                                                <span class="star empty">&#9733;</span>
                                                <span class="star empty">&#9733;</span>
                                                <span class="star empty">&#9733;</span>
                                           </div>
                                           <span class="rating-value">{{ recipe.rating }}</span><span>/5</span>
                                       </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
<!-- Pagination controls -->
<nav aria-label="Page navigation" style="padding-top: 20px;">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><span class="page-link">{{ num }}</span></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
        {% endif %}
    </ul>
</nav>

    
    <script src="{% static 'js/star_rating.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const cardBody = document.querySelectorAll('.card-body');
            cardBody.forEach(container => {
                let rating = parseFloat(container.dataset.rating);
                rating = Math.round(rating * 100) / 100;

                const starRatingElement = container.querySelector('.star-rating');
                viewStars(starRatingElement, rating);

                const ratingValueElement = container.querySelector('.rating-value');
                ratingValueElement.textContent = rating.toFixed(2); 
            });
        });
    </script>

{% endblock %}